### ISSUE TITLE
Releasing pre-trained tokenizer

### ISSUE THREAD

**Issue by MaksymDel** [RobertKirk/tinystories-wrappers#3]
Hi, thanks for releasing the code and models!
 
The repo seems to miss the pretrained tokenizer. It is easy to train yourself after https://github.com/RobertKirk/tinystories-wrappers/pull/2 is merged, but it would be nice to go with pre-trained models out-of-the-box.

**Comment by RobertKirk** [comment]
Hi, I've added that now, sorry I missed this before. Thanks for point it out.
