### ISSUE TITLE
Releasing models in torch format

### ISSUE THREAD

**Issue by MaksymDel** [RobertKirk/tinystories-wrappers#4]
Thanks again for releasing the pre-trained model!

Do you also have a plan to release them in the format loadable from Pytorch (current .bin files are serialized to be read from C)?

**Comment by RobertKirk** [comment]
Hi, thanks for the issue. I will upload the correct model formats that can be loaded into pytorch in the next day or two, sorry for the incorrect formats before.

**Comment by RobertKirk** [comment]
The new link in the readme should now point to weights loadable in pytorch.
